# coding: utf-8
# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.8.1.dev16+g1be830d.d20220819'
__version_tuple__ = version_tuple = (0, 8, 1, 'dev16', 'g1be830d.d20220819')
